### ISSUE TITLE
Report issues per html filename & not per filepath

### ISSUE THREAD

**Issue by sujanamadhav** [yvanavermaet/gulp-htmllint#18]
Hi,
I see that only single html file name is printed for all the errors under src directory. Is there a way to get each html name and its respective issues reported?

**Comment by yvanavermaet** [comment]
hi @sujanamadhav 

It's been a while since I've worked on this tool. Apologies for the late reply. I was under the assumption that the tool already reported based on filename.

Which configuration do you use? Could you copy and paste your implementation of gulp-htmllint?

Thanks in advance.

Kind regards,
Yannick

**Comment by yvanavermaet** [comment]
Just tested it and that's exactly what the tool does: File > Errors. File > Errors.

If I didn't understand the question, feel free to reopen and add more information.
