### ISSUE TITLE
getting error 'line ending does not match format: lf'

### ISSUE THREAD

**Issue by ritsrivastava01** [yvanavermaet/gulp-htmllint#20]
I have .htmllintrc file with following rule:
{
    "indent-style":"spaces",
    "indent-width":"2"

}

But I m getting the error 'line ending does not match format: lf' How can I disable the rule..???

**Comment by yvanavermaet** [comment]
hi @ritsrivastava01 

This is a question related to htmllint itself, not this tool. However, I can help you out :)

That's due to a default rule called line-end-style. By default the value is "lf". See https://github.com/htmllint/htmllint/wiki/Options#line-end-style for possible values. Use false to disable it.
